[2025-04-25T12:15:54.990-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-25T12:15:55.116-0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_datawarehouse.etl_Produtos manual__2025-04-25T00:00:00+00:00 [queued]>
[2025-04-25T12:15:55.124-0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_datawarehouse.etl_Produtos manual__2025-04-25T00:00:00+00:00 [queued]>
[2025-04-25T12:15:55.125-0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-25T12:15:55.143-0300] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_Produtos> on 2025-04-25 00:00:00+00:00
[2025-04-25T12:15:55.155-0300] {standard_task_runner.py:72} INFO - Started process 71183 to run task
[2025-04-25T12:15:55.163-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_datawarehouse', 'etl_Produtos', 'manual__2025-04-25T00:00:00+00:00', '--job-id', '125', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpfnoxyq3m']
[2025-04-25T12:15:55.167-0300] {standard_task_runner.py:105} INFO - Job 125: Subtask etl_Produtos
[2025-04-25T12:15:55.241-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_datawarehouse.etl_Produtos manual__2025-04-25T00:00:00+00:00 [running]> on host jonathan-brito
[2025-04-25T12:15:55.353-0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='etl_datawarehouse' AIRFLOW_CTX_TASK_ID='etl_Produtos' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-25T00:00:00+00:00'
[2025-04-25T12:15:55.359-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-25T12:15:55.359-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-25T12:15:55.359-0300] {logging_mixin.py:190} INFO - Current task name:etl_Produtos state:running start_date:2025-04-25 15:15:55.116693+00:00
[2025-04-25T12:15:55.360-0300] {logging_mixin.py:190} INFO - Dag name:etl_datawarehouse and current dag run status:running
[2025-04-25T12:15:55.360-0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-25T12:15:56.842-0300] {logging_mixin.py:190} INFO - Conex√£o com o PostgreSQL bem-sucedida - 2025-04-25 12:15:56.842869
[2025-04-25T12:16:07.901-0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 240, in etl_callable
    result = getattr(service, process_method)()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 111, in process_product_dimension
    return self._process_dimension('transform_product_dimension', '_insert_product_dimension')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 91, in _process_dimension
    getattr(self, insert_method)(chunk)
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 193, in _insert_product_dimension
    cursor.execute(query, (
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2025-04-25T12:16:07.938-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-25T12:16:07.940-0300] {logging_mixin.py:190} INFO - Task start:2025-04-25 15:15:55.116693+00:00 end:2025-04-25 15:16:07.936555+00:00 duration:12.819862
[2025-04-25T12:16:07.941-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): etl_Produtos> dag:<DAG: etl_datawarehouse> dagrun:<DagRun etl_datawarehouse @ 2025-04-25 00:00:00+00:00: manual__2025-04-25T00:00:00+00:00, state:running, queued_at: 2025-04-25 15:12:39.084954+00:00. externally triggered: True>
[2025-04-25T12:16:07.942-0300] {logging_mixin.py:190} INFO - Failure caused by there is no unique or exclusion constraint matching the ON CONFLICT specification
[2025-04-25T12:16:07.943-0300] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_datawarehouse, task_id=etl_Produtos, run_id=manual__2025-04-25T00:00:00+00:00, execution_date=20250425T000000, start_date=20250425T151555, end_date=20250425T151607
[2025-04-25T12:16:08.017-0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-25T12:16:08.018-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 125 for task etl_Produtos (there is no unique or exclusion constraint matching the ON CONFLICT specification
; 71183)
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 240, in etl_callable
    result = getattr(service, process_method)()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 111, in process_product_dimension
    return self._process_dimension('transform_product_dimension', '_insert_product_dimension')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 91, in _process_dimension
    getattr(self, insert_method)(chunk)
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 193, in _insert_product_dimension
    cursor.execute(query, (
psycopg2.errors.InvalidColumnReference: there is no unique or exclusion constraint matching the ON CONFLICT specification

[2025-04-25T12:16:08.079-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-25T12:16:08.119-0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T12:16:08.120-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
