[2025-04-25T12:42:22.077-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-25T12:42:22.188-0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_datawarehouse.etl_tempo_entrega manual__2025-04-25T00:00:00+00:00 [queued]>
[2025-04-25T12:42:22.199-0300] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_datawarehouse.etl_tempo_entrega manual__2025-04-25T00:00:00+00:00 [queued]>
[2025-04-25T12:42:22.199-0300] {taskinstance.py:2867} INFO - Starting attempt 1 of 3
[2025-04-25T12:42:22.228-0300] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): etl_tempo_entrega> on 2025-04-25 00:00:00+00:00
[2025-04-25T12:42:22.241-0300] {standard_task_runner.py:72} INFO - Started process 96033 to run task
[2025-04-25T12:42:22.251-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_datawarehouse', 'etl_tempo_entrega', 'manual__2025-04-25T00:00:00+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmpqdzxq4t5']
[2025-04-25T12:42:22.253-0300] {standard_task_runner.py:105} INFO - Job 129: Subtask etl_tempo_entrega
[2025-04-25T12:42:22.335-0300] {task_command.py:467} INFO - Running <TaskInstance: etl_datawarehouse.etl_tempo_entrega manual__2025-04-25T00:00:00+00:00 [running]> on host jonathan-brito
[2025-04-25T12:42:22.402-0300] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data Team' AIRFLOW_CTX_DAG_ID='etl_datawarehouse' AIRFLOW_CTX_TASK_ID='etl_tempo_entrega' AIRFLOW_CTX_EXECUTION_DATE='2025-04-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-25T00:00:00+00:00'
[2025-04-25T12:42:22.403-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-25T12:42:22.403-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-25T12:42:22.403-0300] {logging_mixin.py:190} INFO - Current task name:etl_tempo_entrega state:running start_date:2025-04-25 15:42:22.189219+00:00
[2025-04-25T12:42:22.403-0300] {logging_mixin.py:190} INFO - Dag name:etl_datawarehouse and current dag run status:running
[2025-04-25T12:42:22.403-0300] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-25T12:42:23.892-0300] {logging_mixin.py:190} INFO - Conex√£o com o PostgreSQL bem-sucedida - 2025-04-25 12:42:23.892327
[2025-04-25T12:42:37.381-0300] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 240, in etl_callable
    result = getattr(service, process_method)()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 105, in process_timeship_dimension
    return self._process_dimension('transform_timeship_dimension', '_insert_timeship_dimension')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 80, in _process_dimension
    transformed_df = getattr(ETLSalesPipelines, transform_method)(df)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 23, in transform_timeship_dimension
    df['data_envio'] = pd.to_datetime(df['data_envio'])
                                      ~~^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'data_envio'
[2025-04-25T12:42:37.390-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-25T12:42:37.390-0300] {logging_mixin.py:190} INFO - Task start:2025-04-25 15:42:22.189219+00:00 end:2025-04-25 15:42:37.389541+00:00 duration:15.200322
[2025-04-25T12:42:37.391-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): etl_tempo_entrega> dag:<DAG: etl_datawarehouse> dagrun:<DagRun etl_datawarehouse @ 2025-04-25 00:00:00+00:00: manual__2025-04-25T00:00:00+00:00, state:running, queued_at: 2025-04-25 15:23:52.078945+00:00. externally triggered: True>
[2025-04-25T12:42:37.392-0300] {logging_mixin.py:190} INFO - Failure caused by 'data_envio'
[2025-04-25T12:42:37.392-0300] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_datawarehouse, task_id=etl_tempo_entrega, run_id=manual__2025-04-25T00:00:00+00:00, execution_date=20250425T000000, start_date=20250425T154222, end_date=20250425T154237
[2025-04-25T12:42:37.424-0300] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-25T12:42:37.425-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 129 for task etl_tempo_entrega ('data_envio'; 96033)
Traceback (most recent call last):
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 240, in etl_callable
    result = getattr(service, process_method)()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 105, in process_timeship_dimension
    return self._process_dimension('transform_timeship_dimension', '_insert_timeship_dimension')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 80, in _process_dimension
    transformed_df = getattr(ETLSalesPipelines, transform_method)(df)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/dags/dag_etl.py", line 23, in transform_timeship_dimension
    df['data_envio'] = pd.to_datetime(df['data_envio'])
                                      ~~^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/pandas/core/series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/pandas/core/series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jonathan-brito/python-projects/airflow/venv/lib/python3.12/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'data_envio'
[2025-04-25T12:42:37.445-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-25T12:42:37.460-0300] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-25T12:42:37.461-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
